/** `auth_outcome_enum` (ARCHITECTURE §4.1). */
export enum AuthOutcome {
  SUCCESS = 'SUCCESS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  LOCKED = 'LOCKED',
  TWOFA_FAILED = 'TWOFA_FAILED',
  RATE_LIMITED = 'RATE_LIMITED',
  SUSPENDED = 'SUSPENDED',
}
