/** `quota_reason_enum` (ARCHITECTURE §4.1). */
export enum QuotaReason {
  MONTHLY_GRANT = 'MONTHLY_GRANT',
  OVERRIDE_GRANT = 'OVERRIDE_GRANT',
  GENERATION_CONSUMED = 'GENERATION_CONSUMED',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}
