/** `usage_reason_enum` (ARCHITECTURE §4.1). */
export enum UsageReason {
  MONTHLY_BUDGET_GRANT = 'MONTHLY_BUDGET_GRANT',
  CONSUMER_GENERATION = 'CONSUMER_GENERATION',
  TEST_RENDER = 'TEST_RENDER',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}
