/**
 * WCAG 2.1 relative luminance and contrast, plus a minimal reader for the one file in the
 * frontend that may hold a raw colour (`../styles/tokens.css`).
 *
 * This exists so the ratios quoted in ARCHITECTURE §6.1 are *computed* from the shipped token
 * values rather than trusted from a comment. It is deliberately dependency-free and pure: the
 * only input is the stylesheet text, so it runs in a plain Node test environment with no
 * browser and no DOM.
 *
 * Formulae: WCAG 2.1 §"relative luminance" and §"contrast ratio".
 */

export interface Rgb {
  r: number;
  g: number;
  b: number;
}

/** Parses `#rgb`, `#rrggbb` and `rgb(r g b / a)`. Returns `null` for keywords and `var()`. */
export function parseColor(value: string): Rgb | null {
  const input = value.trim();

  const hex = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(input);
  if (hex) {
    const digits = hex[1] ?? '';
    const full =
      digits.length === 3
        ? digits
            .split('')
            .map((char) => char + char)
            .join('')
        : digits;
    return {
      r: Number.parseInt(full.slice(0, 2), 16),
      g: Number.parseInt(full.slice(2, 4), 16),
      b: Number.parseInt(full.slice(4, 6), 16),
    };
  }

  const rgb = /^rgba?\(\s*([0-9.]+)[\s,]+([0-9.]+)[\s,]+([0-9.]+)/i.exec(input);
  if (rgb) {
    return {
      r: Number(rgb[1]),
      g: Number(rgb[2]),
      b: Number(rgb[3]),
    };
  }

  return null;
}

/** WCAG 2.1 relative luminance of an sRGB colour. */
export function relativeLuminance({ r, g, b }: Rgb): number {
  const channel = (raw: number): number => {
    const c = raw / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
}

/** WCAG 2.1 contrast ratio between two colours, from 1 to 21. Order does not matter. */
export function contrastRatio(foreground: string, background: string): number {
  const fg = parseColor(foreground);
  const bg = parseColor(background);
  if (!fg || !bg) {
    throw new Error(`Not a resolvable colour: ${!fg ? foreground : background}`);
  }
  const a = relativeLuminance(fg);
  const b = relativeLuminance(bg);
  const lighter = Math.max(a, b);
  const darker = Math.min(a, b);
  return (lighter + 0.05) / (darker + 0.05);
}

/**
 * Pulls the custom properties out of one top-level rule of `tokens.css`.
 *
 * A hand-rolled reader rather than a CSS parser dependency: the file is generated by nobody and
 * edited by hand, its shape is fixed by §6.1, and a parser would be a build-time dependency
 * added purely for a test.
 */
export function readTokenBlock(css: string, selector: string): Record<string, string> {
  const index = css.indexOf(`\n${selector} {`);
  if (index === -1) {
    throw new Error(`tokens.css has no \`${selector}\` block`);
  }
  const start = css.indexOf('{', index) + 1;

  let depth = 1;
  let cursor = start;
  while (cursor < css.length && depth > 0) {
    const char = css[cursor];
    if (char === '{') depth += 1;
    if (char === '}') depth -= 1;
    cursor += 1;
  }

  const body = css.slice(start, cursor - 1);
  const tokens: Record<string, string> = {};

  // Strip comments first so a `/* 5.9:1 */` note can never be read as a value.
  for (const line of body.replace(/\/\*[\s\S]*?\*\//g, '').split(';')) {
    const declaration = /^\s*(--[a-z0-9-]+)\s*:\s*([\s\S]+?)\s*$/i.exec(line);
    if (declaration) {
      const name = declaration[1];
      const value = declaration[2];
      if (name && value) tokens[name] = value;
    }
  }

  return tokens;
}
